[buildPlans.Tepiosevka]
family = "Tepiosevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.Tepiosevka.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "two-arcs"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "closed-contour"
seven = "straight-serifless"
eight = "crossing"
nine = "closed-contour"
zero = "oval-dotted"
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-h = "serifless"
capital-i = "serifless"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-asymmetric-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
b = "toothless-rounded-serifless"
c = "serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-earless-rounded"
h = "straight-serifless"
i = "serifed-flat-tailed"
j = "flat-hook-serifless"
k = "symmetric-touching-serifless"
l = "serifed-flat-tailed"
m = "earless-rounded-double-arch-serifless"
n = "earless-rounded-straight-serifless"
p = "eared-serifless"
q = "earless-rounded-straight-serifless"
r = "hookless-serifless"
s = "serifless"
t = "flat-hook"
u = "toothless-rounded-serifless"
v = "straight-serifless"
w = "straight-asymmetric-serifless"
x = "straight-serifless"
y = "cursive-serifless"
z = "straight-serifless"
long-s = "flat-hook-serifless"
eszet = "sulzbacher-serifless"
lower-eth = "straight-bar"
lower-thorn = "serifless"
lower-alpha = "barred"
capital-gamma = "serifless"
capital-delta = "straight"
lower-delta = "flat-top"
lower-iota = "hooky-bottom"
capital-lambda = "straight-serifless"
lower-lambda = "straight"
lower-mu = "toothless-rounded-serifless"
lower-xi = "flat-top"
lower-pi = "small-capital"
lower-tau = "tailless"
lower-chi = "straight-serifless"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ze = "serifless"
cyrl-ze = "serifless"
cyrl-capital-ka = "symmetric-connected-serifless"
cyrl-ka = "symmetric-touching-serifless"
cyrl-el = "straight"
cyrl-em = "hanging-serifless"
cyrl-en = "serifless"
cyrl-capital-u = "straight-serifless"
cyrl-ef = "serifless"
cyrl-che = "standard"
cyrl-yeri = "corner"
cyrl-yery = "corner"
cyrl-capital-ya = "straight-serifless"
cyrl-ya = "straight-serifless"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "high"
asterisk = "hex-high"
underscore = "low"
caret = "high"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "large-contour"
brace = "straight"
guillemet = "straight"
number-sign = "upright-open"
ampersand = "closed"
at = "fourfold"
dollar = "open-cap"
cent = "open"
percent = "rings-continuous-slash"
bar = "natural-slope"
question = "corner"
partial-derivative = "straight-bar"
micro-sign = "toothless-rounded-serifless"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.Tepiosevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Tepiosevka.weights.Bold]
shape = 700
menu = 700
css = 700
